name: AccountsHook
author: SkytAsul
api-version: 1.17
version: 2.0.0
description: This plugin allows other plugins to hook easily into accounts systems without needing to hook each plugin (classes plugin...)
main: fr.skytasul.accounts.AccountsPlugin