name: AccountsHook
author: SkytAsul
api-version: 1.13
version: 1.4.0-EXPERIMENTAL
description: This plugin allows other plugins to hook easily into accounts systems without needing to hook each plugin (classes plugin...)
main: fr.skytasul.accounts.AccountsPlugin